### PR TITLE
perf: update to plugin v1 and update settings for mango

### PR DESCRIPTION
**Pull request by Alec4r**
# How to test it
```bash
tvm install v13.3.1
mkdir mango && cd mango
tvm project init mango v13.3.1
source .tvm/bin/activate

tvm plugins install tutor-mfe==13.0.5
tutor plugins enable mfe

tvm plugins install git+https://github.com/eduNEXT/tutor-contrib-edunext-distro@mango
tutor plugins enable distro

tutor config save

tutor distro enable-themes
tutor distro enable-private-packages

tutor local quickstart
tutor local stop

tutor dev init
tutor dev start
tutor dev stop
```

### CODE REVIEW

**Comment by JuanDavidBuitrago** [comment]
There is a problem in Studio, when I test with ``tutor local start`` show:

Screenshot from 2022-06-14 08-23-35

**Review by JuanDavidBuitrago — CHANGES_REQUESTED** [review]
There is a problem in Studio, when I test with tutor local start show:

Screenshot from 2022-06-14 08-23-35

**Comment by Alec4r** [comment]
> There is a problem in Studio, when I test with tutor local start show:
> 
> Screenshot from 2022-06-14 08-23-35

This has fixed, please can you try again?

```bash
tvm plugins install git+https://github.com/eduNEXT/tutor-contrib-edunext-distro@mango
tutor plugins enable distro

tutor config save

tutor local start
```

**Review by dcoa — APPROVED** [review]

**Review by JuanDavidBuitrago — APPROVED** [review]
Excellent! It's working.

**Pull request merged**
