### PR TITLE
docs: distro customization and plugin install

### PR DESCRIPTION
**Pull request by dcoa**
### Description

This PR describes distro settings and how to change them and also describes how to add new packages. 

## How to test 

Check branch files https://github.com/eduNEXT/tutor-contrib-edunext-distro/tree/dcoa/distro-docs-DS-230/docs

### CODE REVIEW

**Review by JuanDavidBuitrago — DISMISSED** [review]
I think the information is complete. Thanks @dcoa

**Review by MaferMazu — COMMENTED** [review]
Thanks, @dcoa; I only suggest adding the link to this doc somewhere in the README to avoid losing information. What do you think?

**Comment by dcoa** [comment]
@MaferMazu please check and let me know if you agree with the README addition.

**Review by MaferMazu — APPROVED** [review]
I agree, thanks, @dcoa 🌟

**Pull request merged**
